logging:
    level:
        com.github.joy.security.admin: DEBUG

spring:
  application:
    name: ace-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.github.joy.security.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml
  
server:
  port: 8762
  
eureka:
  instance:
    status-page-url: /info
    health-check-url: /health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 2000
  # 服务或应用名
  sysName: ace-admin
  enable: true
  database: 0